services:
  apache-php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: APA
    ports:
      - '8080:80'
      - '8081:443'
    extra_hosts:
      - project.local:127.0.0.1

    volumes:
      - ./content:/var/www/localhost/htdocs/content
      - ./config/apache2:/etc/apache2
      - ./config/php84:/etc/php84

    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysqlPHP
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/app/data
